#ifndef CONSTANTS_H
#define CONSTANTS_H

#define READ_ERROR 		1932
#define EXIT_SUCCESS 	0
#define EXIT_FAILURE	1

#define META_COMMAND_SUCCESS 			 0
#define META_COMMAND_FAILURE 			 1
#define META_COMMAND_UNRECOGNIZED	-1

#endif